accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("", views.dashboard, name='dashboard'),
    path('entries', views.entries, name='entries')
]

admins/urls.py
from django.urls import path
from . import views

app_name = 'admins'
urlpatterns = [
    path('attendance', views.attendance, name="attendance"),
    path('create_patient', views.create_patient, name="create_patient"),
    path('edit_patient', views.edit_patient, name="edit_patient"),
    path('create_cases', views.create_case, name="create_case"),
    path('edit_cases', views.edit_case, name="edit_case"),
    path('list_patients', views.list_patients, name="list_patients"),
    path('list_cases', views.list_cases, name="list_cases")
]

api/urls.py
from django.urls import path, include
from pharma import api_views
from rest_framework.authtoken import views
from .views import ping, csrf

urlpatterns = [
   path('api-token-auth/', views.obtain_auth_token),
   path('api-auth/', include('rest_framework.urls')),
   path('last-pres', api_views.LastPrescriptionView.as_view()),
   path('stock', api_views.ListStockView.as_view()),
   path('csrf', csrf),
   path('ping', ping),
]

doctors/urls.py
from django.urls import path
from . import views

app_name = 'doctor'
urlpatterns = [
    path("", views.appointment, name="dashboard"),
    path("case_archive", views.case_archive, name="case_archive"),
    path("recover", views.prescription, name="recover"),
    path("add_prescription", views.add_prescription, name="add_prescription"),
    path("list_medicines", views.list_medicines, name="list_medicines"),
    path("save_prescription", views.save_prescription, name="save_prescription"),
    path("view_history", views.view_history, name="view_history")
]

med_bay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from admins.views import LoginView, confirm_logout, home, redirect_login, set_theme

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('staff/', include('admins.urls')),
    path('doctor/', include('doctors.urls')),
    path('pharmacy/', include('pharma.urls')),
    path('accounts/', include('accounts.urls')),
    path("login", LoginView.as_view(template_name="admins/login.html"), name="login"),
    path("logout", LogoutView.as_view(template_name="admins/logout.html"), name="logout"),
    path("confirm", confirm_logout, name='confirm_logout'),
    path("", home, name="home"),
    path("redirect", redirect_login, name="red"),
    path("set_theme", set_theme, name="set_theme")
]


handler404 = 'med_bay.error_views.error_404_handler'
handler403 = 'med_bay.error_views.error_403_handler'

pharma/urls.py
from django.urls import path
from . import views

app_name = 'pharma'
urlpatterns = [
    path("", views.shop, name="shop"),
    path("place", views.place, name="place"),
    path("bill_info", views.bill_info, name="bill_info"),
    path("remove", views.remove, name="remove"),
    path("add_one", views.add_one, name="add"),
    path("add_stock", views.add_stock, name="add_stock"),
    path("remove_stock", views.remove_stock, name="remove_stock"),
    path("bill", views.bill, name="bill"),
    path("cart", views.cart, name="cart"),
    path('bill_archive', views.bill_archive, name="bill_archive"),
    path("bill_archive_viewer", views.bill_archive_viewer, name="bill_archive_viewer"),
    path("order_prescription", views.order_prescription, name="order_prescription"),
    path("edit_prescription", views.edit_prescription, name="edit_prescription")
]

admins/templates/template.html
<!DOCTYPE html>
{%load static%}
<html>
    <head>
        <title>Med-Bay</title>
        <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
        <!-- setting the theme of the website -->

        <link rel="stylesheet" id="css" type="text/css" href="{% static 'style.css' %}">
        {% if request.COOKIES.theme == "d" %}
        <link rel="stylesheet" id="css" type="text/css" href="{% static 'dark_theme.css' %}">
        {% endif %}
<!--        scripts-->
        <script type="text/javascript" src="{% static 'template.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        {%block script%}
        
        {%endblock%}
<!--        scripts-->
    </head>

    <body onload="showLogo()">
        <div id="loadLogo"><img id="loadLogoImg" src="{%static 'images/med-bay.png'%}" alt="med-bay logo"></div>
        <div class="floating-bar" id="floating-bar">
            <div class="nav-bar">
                <button class="side-bar-btn" value="click" onclick="closeSidebar()">
                    <img class="side-bar-btn-icon" src="{% static 'images/menu.svg' %}" margin="0" height="100%" alt="menu">
                </button>
                <div id="logo-div">
                    <img id="logo" onclick="document.location='{% url 'red' %}'" src="{% static 'images/med-bay.png' %}" alt="med-bay logo">
                </div>
                <div class="user-btns">
                    <button class="user-btn" onclick="toggleTheme()" title="Toggle Theme">
                        {% if not request.COOKIES.theme %}
                        <img id="theme-button" class="user-btn-img" src="{% static 'images/dark.png' %}">
                        {% elif request.COOKIES.theme == "w" %}
                        <img id="theme-button" class="user-btn-img" src="{% static 'images/dark.png' %}">
                        {% elif request.COOKIES.theme == "d" %}
                        <img id="theme-button" class="user-btn-img" src="{% static 'images/light.png' %}">
                        {% endif %}
                    </button>
                    <button class="user-btn">
                        {% if not request.user.is_authenticated %}
                        <img class="user-btn-img" onclick="location='{% url 'login' %}'" title="You are not logged in" src="{% static 'images/user.png' %}" height="40vh" alt="user icon">
                        {% else %}
                        <img class="user-btn-img" onclick="location='{% url 'confirm_logout' %}'" title="You are {{user}}" src="{% static 'images/user_loggedin.png' %}" height="40vh" alt="logged in user icon">
                        {%endif%}
                    </button>
                </div>
            </div>
        </div>
        <div class="side-bar">
            <div class="side-bar-top">
                <button class="side-bar-btn" value="click" onclick="closeSidebar()">
                    <img class="side-bar-btn-icon" src="{% static 'images/menu.svg' %}" margin="0" height="100%" alt="menu">
                </button>
                <label>Go to</label>
            </div>
            <ul id="nav-list">
                <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                {% if user.staff.role == "d" %}
                <a class="nav-link" href="{% url 'doctor:dashboard' %}"><li class="nav-item">Doctor's Dashboard</li></a>
                <a class="nav-link" href="{% url 'doctor:recover' %}"><li class="nav-item">Recover Unsaved Prescriptions</li></a>
                <a class="nav-link" href="{% url 'doctor:case_archive' %}"><li class="nav-item">Patient Archive</li></a>
                {% elif user.staff.role == "p" %}
                <a class="nav-link" href="{% url 'pharma:shop' %}"><li class="nav-item">Pharmacy</li></a>
                <a class="nav-link" href="{% url 'pharma:bill_archive' %}"><li class="nav-item">Bill Archive</li></a>
                <a class="nav-link" href="{% url 'pharma:order_prescription' %}"><li class="nav-item">Prescription Orders</li></a>
                {% elif user.staff.role == "a" %}
                <a class="nav-link" href="{% url 'admins:attendance' %}"><li class="nav-item">Doctor Attendance</li></a>
                <a class="nav-link" href="{% url 'admins:list_patients' %}"><li class="nav-item">Patients List</li></a>
                <a class="nav-link" href="{% url 'admins:list_cases' %}"><li class="nav-item">Cases List</li></a>
                <a class="nav-link" href="{% url 'admins:create_patient' %}"><li class="nav-item">Create Patient</li></a>
                <a class="nav-link" href="{% url 'admins:create_case' %}"><li class="nav-item">Create Case</li></a>
                {% elif user.staff.role == "ac" %}
                <a class="nav-link" href="{% url 'accounts:dashboard' %}"><li class="nav-item">Dashboard</li></a>
                <a class="nav-link" href="{% url 'accounts:entries' %}"><li class="nav-item">Chart Of Accounts</li></a>
                {%endif%}
            </ul>
        </div>
        <div class="main">
            {%block body%}
                
            {%endblock%}
        </div>
        {% comment %} <div class="root-grid" id="root-grid">
            
            
        </div> {% endcomment %}
        <div class="footer">
            <label>Med-Bay Team DeBug &copy; 2021</label>
        </div>
    </body>
</html>