api/urls.py
from django.urls import path, include
from pharma import api_views
from rest_framework.authtoken import views
from .views import ping, csrf

urlpatterns = [
   path('api-token-auth/', views.obtain_auth_token),
   path('api-auth/', include('rest_framework.urls')),
   path('last-pres', api_views.LastPrescriptionView.as_view()),
   path('stock', api_views.ListStockView.as_view()),
   path('csrf', csrf),
   path('ping', ping),
]

doctors/urls.py
from django.urls import path
from . import views

app_name = 'doctor'
urlpatterns = [
    path("", views.appointment, name="dashboard"),
    path("case_archive", views.case_archive, name="case_archive"),
    path("recover", views.prescription, name="recover"),
    path("add_prescription", views.add_prescription, name="add_prescription"),
    path("list_medicines", views.list_medicines, name="list_medicines"),
    path("save_prescription", views.save_prescription, name="save_prescription"),
    path("view_history", views.view_history, name="view_history")
]

med_bay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from admins.views import LoginView, confirm_logout, home, redirect_login, set_theme

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('staff/', include('admins.urls')),
    path('doctor/', include('doctors.urls')),
    path('pharmacy/', include('pharma.urls')),
    path('accounts/', include('accounts.urls')),
    path("login", LoginView.as_view(template_name="admins/login.html"), name="login"),
    path("logout", LogoutView.as_view(template_name="admins/logout.html"), name="logout"),
    path("confirm", confirm_logout, name='confirm_logout'),
    path("", home, name="home"),
    path("redirect", redirect_login, name="red"),
    path("set_theme", set_theme, name="set_theme")
]


handler404 = 'med_bay.error_views.error_404_handler'
handler403 = 'med_bay.error_views.error_403_handler'

pharma/urls.py
from django.urls import path
from . import views

app_name = 'pharma'
urlpatterns = [
    path("", views.shop, name="shop"),
    path("place", views.place, name="place"),
    path("bill_info", views.bill_info, name="bill_info"),
    path("remove", views.remove, name="remove"),
    path("add_one", views.add_one, name="add"),
    path("add_stock", views.add_stock, name="add_stock"),
    path("remove_stock", views.remove_stock, name="remove_stock"),
    path("bill", views.bill, name="bill"),
    path("cart", views.cart, name="cart"),
    path('bill_archive', views.bill_archive, name="bill_archive"),
    path("bill_archive_viewer", views.bill_archive_viewer, name="bill_archive_viewer"),
    path("order_prescription", views.order_prescription, name="order_prescription"),
    path("edit_prescription", views.edit_prescription, name="edit_prescription")
]

pharma/models.py
from django.db import models
from admins.models import Staff
from patients.models import Cases


# Create your models here.
class Stock(models.Model):

    name = models.CharField(max_length=30)
    desc = models.TextField()
    price = models.IntegerField()
    quantity = models.IntegerField(default=0)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name}"


# Bill
class Bill(models.Model):

    name = models.CharField(max_length=50)
    contact_num = models.CharField(max_length=10)
    date = models.DateTimeField()

    def __str__(self):
        return f'bill-id: {self.id}| date: {self.date}'


# Prescription
class Prescription(models.Model):

    status_list = (("c", "Created"), ('p', 'Prescribed'), ('d', 'Delivered'))

    bill = models.OneToOneField(Bill, on_delete=models.SET_NULL, null=True)
    case = models.OneToOneField(Cases, on_delete=models.SET_NULL, null=True)
    status = models.CharField(default='c', max_length=2, choices=status_list)

    def __str__(self):
        return f'{self.id}'


# Orders unit
class Order(models.Model):

    user = models.ForeignKey(Staff, on_delete=models.CASCADE)
    item = models.ForeignKey(Stock, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.user.user.username}, {self.item.name}'


# Medicine in prescription
class Medicine(models.Model):

    prescription = models.ForeignKey(Prescription, on_delete=models.CASCADE)
    item = models.ForeignKey(Stock, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.prescription.id},{self.item.name}, {self.quantity}'


class EditedPrescription(models.Model):

    pres = models.OneToOneField(Prescription, on_delete=models.CASCADE)
    user = models.ForeignKey(Staff, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"pres: {self.pres.id} edited by {self.user.user.username}"


# Medicine in prescription
class EPMedicine(models.Model):

    prescription = models.ForeignKey(EditedPrescription, on_delete=models.CASCADE, related_name='medicines')
    item = models.ForeignKey(Stock, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.prescription.id},{self.item.name}, {self.quantity}'


# part of the bill
class BillUnit(models.Model):

    bill = models.ForeignKey(Bill, models.CASCADE)
    name = models.CharField(max_length=30)
    desc = models.TextField()
    price = models.IntegerField()
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name}"

pharma/forms.py
from django import forms

class StockForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'item-detail',
                                                         'id':'name',
                                                         'name':'name',
                                                         'placeholder':'Medicine'}))
    
    price = forms.CharField(widget=forms.NumberInput(attrs={'class':'item-detail',
                                                            'id':'cost',
                                                            'name':'price',
                                                            'placeholder':'100'}))
    
    quantity = forms.CharField(widget=forms.NumberInput(attrs={'class':'item-detail',
                                                               'id':'amount',
                                                               'name':'quantity',
                                                               'placeholder':'100'}))

class BillForm(forms.Form):
    name =  forms.CharField(widget=forms.TextInput(attrs={'class': 'form-input',
                                                           'id': 'name',
                                                           'placeholder': 'Name',
                                                           'autofocus': ''}))
    
    phone = forms.CharField(widget=forms.NumberInput(attrs={'class': "form-input",
                                                            'id': 'phone',
                                                            'placeholder': '1234567890',
                                                            'min': 1000000000,
                                                            'max': 9999999999,
                                                            'autofocus': ''}))

pharma/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from admins.utils import validate_access
from .forms import StockForm, BillForm
from django.http import HttpResponse
from django.utils import timezone
from .models import *
from . import utils
import json


# Create your views here.
@login_required()
def shop(request):

    # Checking if user is allowed visit the site
    validate_access(request, 'p')

    # Getting the list of stocks
    items = Stock.objects.filter(deleted=False)
    items = list(items)
    for item in items:

        # Removing out of stock items
        if item.quantity < 1:
            items.remove(item)

    print(render(request, "pharma/shop.html", context={'items': items}).content)
    return render(request, "pharma/shop.html", context={'items': items})


# Placing order when order button is pressed
@login_required()
def place(request):

    user = validate_access(request, 'p')
    ID = request.GET['product_id']
    qty = int(request.GET['product_amount'])
    item = Stock.objects.filter(id=ID)[0]
    orders = user.staff.order_set.all()

    # Checking if item already in cart
    in_cart = False
    for order in orders:
        if order.item.id == item.id:
            in_cart = True

    # If the item is already in cart
    if in_cart:
        order = user.staff.order_set.filter(item__id=item.id)[0]
        order.quantity += qty

    # Creating a new order if not already there
    else:
        order = Order(user=user.staff, item=item, quantity=qty)

    # Updating the item stock and saving changes
    item.quantity -= qty
    order.save()
    item.save()

    return HttpResponse("success")


@login_required()
def remove(request):

    user = validate_access(request, 'p')

    # Getting the item id and quantity to reduce from request
    ID = int(request.GET['product_id'])
    reduce = int(request.GET['remove_amount'])

    # Getting the respective items and objects from the table
    item = Stock.objects.filter(id=ID)[0]
    order = user.staff.order_set.filter(item__id=item.id)[0]

    # Checking if the quantity in order will be 0
    if order.quantity == reduce:
        order.delete()
    else:
        order.quantity -= reduce
        order.save()

    # Updating item quantity and saving changes
    item.quantity += reduce
    item.save()

    return render(request, "pharma/cart.html", {'cart': cart})


@login_required()
def add_one(request):

    user = validate_access(request, "p")

    # Getting the product id from the request
    ID = int(request.GET['product_id'])

    # Getting the respective items and orders
    item = Stock.objects.get(id=ID)
    order = user.staff.order_set.get(item__id=item.id)

    # Changing the quantity accordingly
    order.quantity += 1
    item.quantity -= 1

    # Saving the changes
    order.save()
    item.save()

    return render(request, "pharma/cart.html", {'cart': cart})


@login_required()
def cart(request):

    user = validate_access(request, 'p')

    orders = user.staff.order_set.all()
    total = utils.get_total(orders)

    return render(request, "pharma/cart.html", {'cart': orders, 'total': total})


# Getting the name and phone number for bill
@login_required()
def bill_info(request):

    # Getting the orders
    user = validate_access(request, 'p')
    orders = user.staff.order_set.all()
    print(orders)
    print(request.GET)

    # Redirecting back to home if there are no orders
    if not orders:
        return redirect("pharma:shop")

    # Checking if the form data is recieved
    if request.method == "POST":
        form = BillForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']
            phone = form.cleaned_data['phone']

            # Redirecting user to prescription page
            response = redirect('pharma:bill')
            response['Location'] += f'?name={name}&phone={phone}'
            return response

    else:
        form = BillForm()

    return render(request, "pharma/bill_info.html", context={'form': form})


# showing the bill after purchase
@login_required()
def bill(request):
    
    # Getting the orders
    user = validate_access(request, 'p')
    orders = user.staff.order_set.all()
    print(orders)
    print(request.GET)

    # Redirecting back to home if there are no orders
    if not orders:
        return redirect("pharma:shop")

    # Generating the bill objects
    bill = utils.generate_bill(name=request.GET["name"], contact_num=request.GET["phone"],
                               date=timezone.now(), orders=orders)

    # Clearing the cart
    for order in orders:
        order.delete()

    # getting all the bill units to send in context
    bill_units = bill.billunit_set.all()
    print(bill_units, bill)
    total = utils.get_bill_total(bill_units)

    return render(request, 'pharma/bill.html', context={'bill': bill, 'bill_unit': bill_units, 'total': total})


@login_required()
def add_stock(request):
    validate_access(request, 'p')
    if request.method == "POST":
        form = StockForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']
            price = form.cleaned_data['price']
            quantity = form.cleaned_data['quantity']

            stock = Stock.objects.create(name=name, desc="med", price=price, quantity=quantity)
            stock.save()

            return redirect("pharma:shop")

    return render(request, 'pharma/add_stock.html')


@login_required()
def remove_stock(request):

    # making sure the user is a pharmacist
    validate_access(request, "p")

    # Deleting the product if product_id is sent
    if 'product_id' in request.GET:
        print(f"deleting {request.GET['product_id']}")
        id = int(request.GET['product_id'])
        item = Stock.objects.get(id=id)
        item.deleted = True
        item.save()

    # loading the list of stocks
    items = Stock.objects.filter(deleted=False)

    return render(request, 'pharma/remove_stock.html', context={'items': items})


# Bill archive
@login_required()
def bill_archive(request):
    validate_access(request, 'p')
    bills = Bill.objects.all()
    return render(request, 'pharma/bill_archive.html', context={"bills": bills})


# Bill archive viewer
def bill_archive_viewer(request):

    bill = Bill.objects.get(id=int(request.GET['id']))
    bill_units = bill.billunit_set.all()
    total = utils.get_bill_total(bill_units)

    return render(request, 'pharma/bill.html', context={'bill': bill, 'bill_unit': bill_units, 'total': total})


@login_required()
def order_prescription(request):
    validate_access(request, 'p')
    prescriptions = Prescription.objects.filter(status='p')

    # placing order if request has id
    if 'id' in request.GET:
        pres = prescriptions.get(id=int(request.GET['id']))

        # returning a redirect if medicine is not available
        issue_stock = {}
        for med in pres.medicine_set.all():
            if med.quantity > med.item.quantity or med.item.deleted:
                issue_stock[med.item.id] = med.item.name

        # if There are missing stock or out of stock medicines
        if issue_stock:
            return HttpResponse(json.dumps(issue_stock), content_type='application/json', status=418)

        # Generating the bill if the objects are in stock
        bill = utils.generate_bill(name=pres.case.patient.name, contact_num=pres.case.patient.phone,
                                   date=timezone.now(), orders=pres.medicine_set.all())

        # Updating the prescription status and saving changes
        pres.bill = bill
        pres.status = 'd'
        pres.save()

        # giving a redirect to view the bill
        return HttpResponse(json.dumps({'id': bill.id}), content_type='application/json')

    return render(request, 'pharma/orders.html', context={'prescriptions': prescriptions})


@login_required()
def edit_prescription(request):
    user = validate_access(request, 'p')

    pres = Prescription.objects.get(id=int(request.GET["id"]))

    # if the list was edited
    if 'save' in request.GET:
        medicine_ids = json.loads(request.GET['medicines'])
        items = Stock.objects.filter(deleted=False)
        epres = EditedPrescription(user=user.staff, pres=pres)
        epres.save()

        for med_id in medicine_ids:
            item = items.get(id=med_id)
            med = EPMedicine(prescription=epres, item=item, quantity=int(medicine_ids[med_id]))
            med.save()
            print(med, 'saved')

        bill = utils.generate_bill(name=pres.case.patient.name, contact_num=pres.case.patient.phone,
                                   date=timezone.now(), orders=epres.medicines.all())

        for med in epres.medicines.all():
            print(med)

        pres.bill = bill
        pres.status = 'd'
        pres.save()

        return HttpResponse(json.dumps({'bill_id': bill.id}), content_type='application/json')

    # getting valid medicines from stock
    all_medicines = []
    for medicine in Stock.objects.filter(deleted=False):
        if medicine.quantity > 0: all_medicines.append(medicine)

    medicines = json.loads(request.GET['medicines'])
    return render(request, 'pharma/edit_prescription.html', context={'prescription': pres,
                                                                     'missing_stock': medicines,
                                                                     'all_medicines': all_medicines})

pharma/templates/pharma/cart.html
{%extends "template.html" %}

{%block body%}
<div class="root-container">
    <span style="display: flex; align-content: space-between; align-items: flex-start">
        <h3 class="list-title">Items In Cart</h3><br>
        <button class="item-detail default-button" id="return-pharma-btn" onclick="document.location='{% url 'pharma:shop' %}'">Back to Pharmacy</button>
    </span>
    <div class="list-container">
        {% if cart %}
        {% for order in cart %}
        <div id="{{order.id}}" class="container" style="width: 20vw;">
            <label class="item-detail-label">Item: </label>
            <input class="item-detail" id="{{order.item.id}}_name" type="text" value="{{order.item.name}}" readonly><br>
            <label class="item-detail-label">Amount:</label>
            <input class="item-detail" id="{{order.item.id}}_amount" type="number" value="{{order.quantity}}" readonly>
            <label class="item-detail-label">Total: </label>
            <span class="item-detail" tabindex="0"><span class="stock-price">&#8377;</span> <input tabindex="-1" class="stock-price" id="age" type="text" value="{% widthratio order.quantity 1 order.item.price %}" pattern="[0-9]+" readonly>
            </span><br>
            <span>
                <br>
                <input class="item-detail" id="remove-from-cart" onclick="removeFromCart({{order.item.id}}, {{order.quantity}})" type="button" value="Remove All">
                <input class="item-detail" id="remove-from-cart" onclick="removeFromCart({{order.item.id}}, 1)" type="button" value="-">
                <input class="item-detail" id="remove-from-cart" onclick="plusone({{order.item.id}})" type="button" value="+">
            </span>
        </div>
        {% endfor %}
        
        <span>
            <h3 id="cart-total" style="margin: 2vh 2vw -2vh 2vw">Grand Total: &#8377;{{total}}</h3>
            <button class="item-detail default-button" id="proceed-checkout-btn" onclick="document.location='{% url 'pharma:bill_info' %}'" style="margin: 2vh 2vw -2vh 2vw; font-size: 3vh">Proceed to checkout</button>
        </span>
        {% else %}
        <span>
            <h3 id="cart-total" style="margin: 2vh 2vw -2vh 2vw">No items in cart. Add items to cart in the shop page.</h3>
            <button class="item-detail default-button" id="proceed-checkout-btn" onclick="document.location='{% url 'pharma:shop' %}'" style="margin: 2vh 2vw -2vh 2vw; font-size: 3vh">Return To Pharmacy</button>
        </span>
        {% endif %}
    </div>
</div>
{%endblock%}

{%block script%}
<script>
function removeFromCart(id, amount) {
    
    var name = $('#' + id + '_name').val();
    
    
    $.ajax({
        url : "{% url 'pharma:remove' %}",
        data : {
            'product_id' : id,
            'remove_amount': amount
        },
        type : 'GET',
        success : function(response) {
            showMessage("Removed " + amount + " Of " + name + " From Cart");
            location.reload();
        },
        error : function(error) {
            showMessage("Error: Unable To Remove From Cart");
            location.reload();
        }
    });
}

function plusone(id) {
    var name = $('#' + id + '_name').val();
    var amount =$('#' + id + '_amount').val();
    amount += 1;
    
    $.ajax({
        url : "{% url 'pharma:add'%}",
        data : {
            'product_id' : id
        },
        type : 'GET',
        success : function(response) {
            location.reload();
        },
        error : function(error) {
            showMessage("Error: Unable To Add To Cart");
            location.reload();
        }
    });
}
</script>
{%endblock%}

pharma/templates/pharma/edit_prescription.html
{%extends "template.html"%}

{%block body%}
<div class="root-container">
    <label id="missing-prescrription-label"></label>
    <h3 class="list-title">Prescription {{prescription.id}}</h3><br>
    <div class="container">
        <label class="detail-label" class="patient-detail-label">Name: </label>
        <input class="item-detail" id="{{prescription.case.id}}_name" type="text" value="{{prescription.case.patient.name}}" readonly><br>
        <div>
            <label class="prescriptions-label">Medicines:</label>
            <div class="prescriptions-list" style="flex-direction: column;">
                {% for medicineP in prescription.medicine_set.all %}
                {% if medicineP.item in all_medicines %}
                <div class="add-medicine medicine-single medicine-existing">
                    <select id="medicine-list">
                        <option id="medicineP.item.id">{{medicineP.item.name}}</option>
                    </select>
                    <input class="item-detail" id="medicine-quantity" type="number" value="{{medicineP.quantity}}" step="1" min="1" max="20" onkeydown="return false" readonly>
                </div>
                {%endif%}
                {%endfor%}
                <div class="add-medicine" onclick="addMedicine()" id="addMedicineBtn">
                    <label onclick="">Add Medicine</label>
                </div>
            </div>
            <button class="item-detail" onclick="savePrescription({{prescription.id}})">Save</button>
        </div>
    </div>
</div>
{%endblock%}

{%block script%}
<script>

    var medicineId = 0;

    function getMedicines() {

        var medicineList;

        $.ajax({
            async: false,
            url: "{% url 'doctor:list_medicines' %}",
            type: 'GET',
            success: function(data){
                medicineList = data;
            }
        });

        return medicineList;
    }

    function addMedicine() {

        var medicines = getMedicines();

        var medicineContainer = $("<div></div>").addClass("add-medicine");

        medicineContainer.addClass("medicine-single");

        medicineContainer.attr("id", medicineId);

        var selector = $("<select></select>").attr("id", "medicine-list");

        var quantity = $("<input>").addClass("item-detail");

        quantity.attr({type:"number", value:"1", step:"1", min:"1", max:"20", onKeyDown:"return false", id:"medicine-quantity"});

        var removeBtn = $("<button>X</button>").addClass("item-detail");

        removeBtn.attr({onclick:"removeMedicine("+medicineId+")"});

        medicineContainer.append(selector, " ", quantity, " ", removeBtn);

        for(var medicine in medicines) {
            var option = $("<option></option>");
            option.text(medicines[medicine]);
            selector.append(option);
        }

        $("#addMedicineBtn").before(medicineContainer);

        medicineId++;
    }

    function removeMedicine(medicineId) {
        $("#"+medicineId).remove();
    }

    function savePrescription(prescriptionId) {
        var medicines = getMedicines();
        var selectedItems = [];
        var finalItems = {};
        var index = 0;

        var medicineContainers = $(".medicine-single");

        for (i = 0; i < medicineContainers.length; i++) {
            var medicineContainer = medicineContainers[i];
            var inputs = medicineContainer.childNodes;
            if (medicineContainer.classList.contains("medicine-existing")) {
                var itemSelector = inputs[1].value;
                var itemQuantity = inputs[3].value;
            } else {
                var itemSelector = inputs[0].value;
                var itemQuantity = inputs[2].value;
            }
            var itemId = 0;
            var values = [];
            for (var medicine in medicines) {
                if (itemSelector === medicines[medicine]) {
                    itemId = medicine;
                }
            }

            values = [itemId, itemQuantity];

            selectedItems[index] = values;
            index++;
        }

        for (var item of selectedItems) {
            if (item[0] in finalItems) {
                finalItems[item[0]] = parseInt(item[1]) + parseInt(finalItems[item[0]]);
                finalItems[item[0]] = finalItems[item[0]].toString();
            } else {
                finalItems[item[0]] = item[1];
            }
        }

        $.ajax({
            url: "{% url 'pharma:edit_prescription'%}",
            type: 'GET',
            data: {
                'id': prescriptionId,
                'medicines': JSON.stringify(finalItems),
                'save': true
            },
            success: function(response) {
                showMessage("Prescription has been saved");
                location="{% url 'pharma:bill_archive_viewer' %}?id="+response['bill_id'];
            },
            error: function() {
                showMessage("Could not save prescription");
            }
        });
    }

</script>
{%endblock%}

pharma/templates/pharma/orders.html
{%extends "template.html"%}

{%block body%}
<div class="root-container">
        <h3 class="list-title">Prescription Orders</h3><br>
    <div class="list-container">
        {% if prescriptions %}
        {% for prescription in prescriptions %}
        <div id="{{prescription.id}}" class="container" style="width: 20vw;">
            <label class="item-detail-label">Prescription ID: {{prescription.id}}</label><br>
            <label class="item-detail-label">Patient:</label>
            <input class="item-detail" id="{{prescription.id}}_patient" type="text" value="{{prescription.case.patient.name}}" readonly><br>
            <label class="item-detail-label">Authorising Doctor:</label>
            <input class="item-detail" id="{{prescription.id}}_doctor" type="text" value="{{prescription.case.doctor.user.user.username}}" readonly><br>
            <label class="item-detail-label">Case No.:</label>
            <input class="item-detail" id="{{prescription.id}}_case" type="text" value="{{prescription.case.id}}" readonly><br>
            <label class="item-detail-label">Medicines Prescribed:</label>
            <span class="item-detail" style="overflow: scroll; height: 8vh">
                {% for medicine in prescription.medicine_set.all %}
                <input class="item-detail" id="{{prescription.id}}_{{medicine.item.name}}" type="text" value="{{medicine.item.name}} x {{medicine.quantity}}" style="background-color: white; color: black" readonly>
                {% endfor %}
            </span>
            <button class="item-detail" onclick="checkout({{prescription.id}})">Checkout Prescription</button>
        </div>
        {% endfor %}
        {% else %}
        <div class="container">
            <label class="item-detail-label">No Prescriptions Ordered</label>
        </div>
        {% endif %}
    </div>
</div>
{%endblock%}

{%block script%}
<script>
    function checkout(prescriptionId) {
        $.ajax({
            url: "{% url 'pharma:order_prescription' %}",
            data: {
                'id': prescriptionId
            },
            success: function(response) {
                location="{% url 'pharma:bill_archive_viewer' %}?id="+response['id'];
            },
            statusCode: {
                418: function(response) {
                    var medicines = response['responseJSON'];
                    for (var medicine in medicines) {
                        showMessage(medicines[medicine] + " Is Out Of Stock");
                    }
                    location="{% url 'pharma:edit_prescription'%}?id="+prescriptionId+"&medicines="+JSON.stringify(medicines);
                }
            }
        });
    }
</script>
{%endblock%}

pharma/templates/pharma/shop.html
{%extends "template.html" %}
{%load static%}

{%block body%}
<div class="root-container">
    <span style="display: flex; align-content: space-between; align-items: flex-start">
        <h3 class="list-title">Items In Stock</h3>
        <button class="item-detail default-button" id="cart-btn" onclick="document.location='{% url 'pharma:cart' %}'">Cart</button><pre>  </pre>
        <button class="item-detail default-button" id="remove-stock-btn" onclick="document.location='{% url 'pharma:remove_stock' %}'">Remove Stocks</button><pre>  </pre>
        <button class="item-detail default-button" id="bill-archive-btn" onclick="document.location='{% url 'pharma:bill_archive' %}'">View Bill Archive</button>
        
    </span>
    <div class="list-container">
        {% if items %}
        {%for item in items%}
        <div id="{{item.id}}" class="container" style="width: 20vw;">
            <label class="item-detail-label">Item: </label>
            <input class="item-detail" id="{{item.id}}_name" type="text" value="{{item.name}}" readonly><br>
            <label class="item-detail-label">Price: </label>
            <span class="item-detail" tabindex="0"><span class="stock-price">&#8377;</span> <input tabindex="-1" class="stock-price" id="age" type="text" value="{{item.price}}" pattern="[0-9]+" readonly></span><br>
                <label class="item-detail-label">Amount:</label>
            <span>
                <input class="item-detail" id="{{item.id}}_amount" type="number" min="1" max="{{item.quantity}}" step="1" value="1">
                <label>/{{item.quantity}}</label><br>
                <input class="item-detail" id="add-to-cart" onclick="addtocart({{item.id}})" type="button" value="Add To Cart">
            </span>
        </div>
        {%endfor%}
        {% else %}
        <div class="container">
            <label class="item-detail-label">No Items In Stock</label>
        </div>
        {% endif %}
        <div id="add-stock" class="container" style="align-content: center; justify-content: center; cursor: pointer; width: 20vw;" onclick="document.location='{% url 'pharma:add_stock' %}'">
            <label style="font-size: 10vh;">+</label>
        </div>
    </div>
</div>
{%endblock%}


{%block script%}
<script>
    function addtocart(id) {
        var name = $('#' + id + '_name').val();
        var inputAmount = $('#' + id + '_amount');
        var amount = inputAmount.val();
        var max = inputAmount.attr("max");
        
        amount = parseInt(amount);
        max = parseInt(max);
        
        if (amount > max) {
            amount = max;
            inputAmount.val(amount.toString());
        } else if ( amount < 1) {
            amount = 1;
            inputAmount.val(amount.toString());
        }
        
        $.ajax({
            url : "{% url 'pharma:place' %}",
            data : {
                'product_id' : id,
                'product_amount': amount
              },
            type : 'GET',
            success : function(response) {
                location.reload();
            },
            error : function(error) {
                showMessage("Error: Unable To Add To Cart");
                location.reload();
            }
        });
    }
</script>
{%endblock%}