api/urls.py
from django.urls import path, include
from pharma import api_views
from rest_framework.authtoken import views
from .views import ping, csrf

urlpatterns = [
   path('api-token-auth/', views.obtain_auth_token),
   path('api-auth/', include('rest_framework.urls')),
   path('last-pres', api_views.LastPrescriptionView.as_view()),
   path('stock', api_views.ListStockView.as_view()),
   path('csrf', csrf),
   path('ping', ping),
]

doctors/urls.py
from django.urls import path
from . import views

app_name = 'doctor'
urlpatterns = [
    path("", views.appointment, name="dashboard"),
    path("case_archive", views.case_archive, name="case_archive"),
    path("recover", views.prescription, name="recover"),
    path("add_prescription", views.add_prescription, name="add_prescription"),
    path("list_medicines", views.list_medicines, name="list_medicines"),
    path("save_prescription", views.save_prescription, name="save_prescription"),
    path("view_history", views.view_history, name="view_history")
]

med_bay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from admins.views import LoginView, confirm_logout, home, redirect_login, set_theme

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('staff/', include('admins.urls')),
    path('doctor/', include('doctors.urls')),
    path('pharmacy/', include('pharma.urls')),
    path('accounts/', include('accounts.urls')),
    path("login", LoginView.as_view(template_name="admins/login.html"), name="login"),
    path("logout", LogoutView.as_view(template_name="admins/logout.html"), name="logout"),
    path("confirm", confirm_logout, name='confirm_logout'),
    path("", home, name="home"),
    path("redirect", redirect_login, name="red"),
    path("set_theme", set_theme, name="set_theme")
]


handler404 = 'med_bay.error_views.error_404_handler'
handler403 = 'med_bay.error_views.error_403_handler'

doctors/models.py
from django.db import models
from admins.models import Staff


# Create your models here.
class Doctor(models.Model):
    user = models.OneToOneField(Staff, on_delete=models.CASCADE)
    speciality = models.CharField(max_length=50)
    availability = models.BooleanField(default=False)
    visit_cost = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user.user.username}"

pharma/models.py
from django.db import models
from admins.models import Staff
from patients.models import Cases


# Create your models here.
class Stock(models.Model):

    name = models.CharField(max_length=30)
    desc = models.TextField()
    price = models.IntegerField()
    quantity = models.IntegerField(default=0)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name}"


# Bill
class Bill(models.Model):

    name = models.CharField(max_length=50)
    contact_num = models.CharField(max_length=10)
    date = models.DateTimeField()

    def __str__(self):
        return f'bill-id: {self.id}| date: {self.date}'


# Prescription
class Prescription(models.Model):

    status_list = (("c", "Created"), ('p', 'Prescribed'), ('d', 'Delivered'))

    bill = models.OneToOneField(Bill, on_delete=models.SET_NULL, null=True)
    case = models.OneToOneField(Cases, on_delete=models.SET_NULL, null=True)
    status = models.CharField(default='c', max_length=2, choices=status_list)

    def __str__(self):
        return f'{self.id}'


# Orders unit
class Order(models.Model):

    user = models.ForeignKey(Staff, on_delete=models.CASCADE)
    item = models.ForeignKey(Stock, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.user.user.username}, {self.item.name}'


# Medicine in prescription
class Medicine(models.Model):

    prescription = models.ForeignKey(Prescription, on_delete=models.CASCADE)
    item = models.ForeignKey(Stock, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.prescription.id},{self.item.name}, {self.quantity}'


class EditedPrescription(models.Model):

    pres = models.OneToOneField(Prescription, on_delete=models.CASCADE)
    user = models.ForeignKey(Staff, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"pres: {self.pres.id} edited by {self.user.user.username}"


# Medicine in prescription
class EPMedicine(models.Model):

    prescription = models.ForeignKey(EditedPrescription, on_delete=models.CASCADE, related_name='medicines')
    item = models.ForeignKey(Stock, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.prescription.id},{self.item.name}, {self.quantity}'


# part of the bill
class BillUnit(models.Model):

    bill = models.ForeignKey(Bill, models.CASCADE)
    name = models.CharField(max_length=30)
    desc = models.TextField()
    price = models.IntegerField()
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name}"

doctors/forms.py
from django import forms


# Case processing form
class CaseProcessing(forms.Form):

    id = forms.IntegerField()

    has_pres = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': "item-detail",
                                                                    'id': "has-prescription",
                                                                    'name': "has-prescription",
                                                                    'type': "checkbox",
                                                                    'default': "false"}), required=False)

    desc = forms.CharField(widget=forms.Textarea(attrs={'class': "item-detail",
                                                        'id': "diagnosis",
                                                        'cols': "16", 'rows': "5",
                                                        'name': "diagnosis",
                                                        'placeholder': "Your Diagnosis"}))

doctors/views.py
from django.contrib.auth.decorators import login_required
from pharma.models import Prescription, Stock, Medicine
from django.shortcuts import render, redirect
from patients.models import Cases, Patient
from admins.utils import validate_access
from django.http import HttpResponse
from .forms import CaseProcessing
from datetime import date
import json


# Create your views here.
@login_required()
def appointment(request):

    # Getting the user from the request
    user = validate_access(request, 'd')

    # Getting the list of patients who are to be attended
    d = date.today()
    cases = user.staff.doctor.cases_set.filter(status="t", appointed_date__date=d)

    # Checking if a patient diagnosis is being sent
    if request.method == "POST":
        form_data = CaseProcessing(request.POST)
        if form_data.is_valid():
            case_id = form_data.cleaned_data['id']

            # Making sure the form is not tamperd with and the case belongs to the doctor
            case = None
            for c in cases:
                if c.id == case_id:
                    case = c

            # if the case belongs to the doctor and is to be handled
            if case:

                # Saving the case data and updating the case state
                case.desc = form_data.cleaned_data['desc']
                case.status = 'd'
                case.save()

                # If the case has a prescription then making one
                if form_data.cleaned_data["has_pres"]:
                    pres = Prescription(case=case)
                    pres.save()

                    # Redirecting user to prescription page
                    response = redirect('doctor:add_prescription')
                    response['Location'] += f'?id={case.id}'
                    return response

            # Redirecting user back to appointments page
            return redirect("doctor:dashboard")

    # If not then just loading the page
    else:
        form = CaseProcessing()
        print(cases)
        return render(request, 'doctors/appointments.html', context={"cases": cases, 'form': form})
    
    
@login_required()
def case_archive(request):
    
    user = validate_access(request, 'd')

    # Getting the cases under the doctor
    cases = user.staff.doctor.cases_set.filter(status='d')
    patients = {}

    # Adding patients as the keys and the done cases as values
    for case in cases:
        if case.patient not in patients:
            patients[case.patient] = case.patient.cases_set.filter(status='d')

    return render(request, 'doctors/case_archive.html', context={'patients': patients})


# Recover prescriptions in case of issues
@login_required()
def prescription(request):
    
    # Getting the user from the request
    user = validate_access(request, 'd')

    # Getting the list of cases
    cases = Cases.objects.filter(doctor=user.staff.doctor)
    prescriptions = []

    for case in cases:
        # checking if prescription exists and the state is created
        if hasattr(case, 'prescription'):
            if case.prescription.status == 'c':
                prescriptions.append(case.prescription)

    return render(request, 'doctors/prescription.html', context={"prescriptions": prescriptions})


@login_required()
def add_prescription(request):
    
    # Getting the user from the request
    validate_access(request, 'd')

    # Getting the case from case id
    case = Cases.objects.get(id=int(request.GET["id"]))

    # Rendering the html file
    return render(request, 'doctors/add-prescription.html', context={"case": case})


# List available medicines
@login_required()
def list_medicines(request):

    all_medicines = []
    for medicine in Stock.objects.filter(deleted=False):
        if medicine.quantity > 0: all_medicines.append(medicine)

    medicines = {}
    for stock in all_medicines:
        medicines[stock.id] = stock.name
    return HttpResponse(json.dumps(medicines), content_type="application/json")


# Saving the prescription
@login_required()
def save_prescription(request):

    # Getting the user from the request
    validate_access(request, 'd')

    # Getting the medicines and the related case
    case = Cases.objects.get(id=int(request.GET['case_id']))
    medicines = json.loads(request.GET["medicines"])

    # Printing the value for debubbing purposes
    print(case, medicines)

    # Making the medicine instances and relating to case
    for med in medicines:
        item = Stock.objects.get(id=int(med))
        medicine = Medicine(prescription=case.prescription, item=item, quantity=int(medicines[med]))
        medicine.save()

    # Updating prescription state
    case.prescription.status = 'p'
    case.prescription.save()

    # returning success message
    return HttpResponse("success")


# View patient history
@login_required()
def view_history(request):
    validate_access(request, 'd')

    # Getting the cases from the request object
    p_id = int(request.GET['id'])
    patient = Patient.objects.get(id=p_id)
    cases = patient.cases_set.filter(status='d')

    return render(request, 'doctors/case-history.html', context={'patient': patient, 'cases': cases})

doctors/templates/doctors/add-prescription.html
{%extends "template.html"%}

{%block body%}
<div class="root-container">
    <h3 class="list-title">Prescription {{case.prescription.id}}</h3><br>
    <div class="container">
        <label class="detail-label" class="patient-detail-label">Name: </label>
        <input class="item-detail" id="{{case.id}}_name" type="text" value="{{case.patient.name}}" readonly><br>
        <div>
            <label class="prescriptions-label">Medicines:</label>
            <div class="prescriptions-list" style="flex-direction: column;">
                <div class="add-medicine" onclick="addMedicine()" id="addMedicineBtn">
                    <label onclick="">Add Medicine</label>
                </div>
            </div>
            <button class="item-detail" onclick="savePrescription({{case.id}})">Save</button>
        </div>
    </div>
</div>
{%endblock%}

{%block script%}
<script>

    var medicineId = 0;
    
    function getMedicines() {
        
        var medicineList;
        
        $.ajax({
            async: false,
            url: "{% url 'doctor:list_medicines' %}",
            type: 'GET',
            success: function(data){
                medicineList = data;
            }
        });
        
        return medicineList;
    }
                    
    function addMedicine() {

        var medicines = getMedicines();
        
        var medicineContainer = $("<div></div>").addClass("add-medicine");
        
        medicineContainer.addClass("medicine-single");
        
        medicineContainer.attr("id", medicineId);

        var selector = $("<select></select>").attr("id", "medicine-list");
        
        var quantity = $("<input>").addClass("item-detail");
        
        quantity.attr({type:"number", value:"1", step:"1", min:"1", max:"20", onKeyDown:"return false", id:"medicine-quantity"});
        
        var removeBtn = $("<button>X</button>").addClass("item-detail");

        removeBtn.attr({onclick:"removeMedicine("+medicineId+")"});

        medicineContainer.append(selector, " ", quantity, " ", removeBtn);
            
        for(var medicine in medicines) {
            var option = $("<option></option>");
            option.text(medicines[medicine]);
            selector.append(option);
        }
        
        $("#addMedicineBtn").before(medicineContainer);

        medicineId++;
    }

    function removeMedicine(medicineId) {
        $("#"+medicineId).remove();
    }
    
    function savePrescription(caseId) {
        var medicines = getMedicines();
        var selectedItems = [];
        var finalItems = {};
        var index = 0;
        
        var medicineContainers = $(".medicine-single");
        
        for (i = 0; i < medicineContainers.length; i++) {
            var medicineContainer = medicineContainers[i];
            var inputs = medicineContainer.childNodes;
            var itemSelector = inputs[0].value;
            var itemQuantity = inputs[2].value;
            var itemId = 0;
            var values = [];            
            for (var medicine in medicines) {
                if (itemSelector === medicines[medicine]) {
                    itemId = medicine;
                }
            }
            
            values = [itemId, itemQuantity];
            
            selectedItems[index] = values;
            index++;
        }
        
        for (var item of selectedItems) {
            if (item[0] in finalItems) {
                finalItems[item[0]] = parseInt(item[1]) + parseInt(finalItems[item[0]]);
                finalItems[item[0]] = finalItems[item[0]].toString();
            } else {
                finalItems[item[0]] = item[1];
            }
        }
        
        
        $.ajax({
            url: "{% url 'doctor:save_prescription'%}",
            type: 'GET',
            data: {
                'case_id': caseId,
                'medicines': JSON.stringify(finalItems)
            },
            success: function() {
                showMessage("Prescription has been saved");
                location="{% url 'doctor:dashboard' %}";
            },
            error: function() {
                showMessage("Could not save prescription");
                location.reload();
            }
        });
    }
    
</script>
{%endblock%}

doctors/templates/doctors/appointments.html
{%extends "template.html" %}

{%block body %}
<!--Full Detail Div-->
<div class="patient-black-out">
{% for case in cases %}
    <div id="{{case.id}}" class="patient-full-container full-container">
        <button class="close-full-btn" onclick="closeCaseFull()">X</button>
        <label class="patient-full-detail-label">Name: </label>
        <input class="item-detail" id="name" type="text" value="{{case.patient.name}}" onclick="copyDetail('name')" readonly><br>
        <label class="patient-full-detail-label">Age: </label>
        <input class="item-detail" id="age" type="text" value="{{case.patient.age}}" pattern="[0-9]+" onclick="copyDetail('age')" readonly><br>
        <label class="patient-full-detail-label">Gender: </label>
        <input class="item-detail" id="gender" type="text" value="{{case.patient.gender | upper}}" size="1" onclick="copyDetail('gender')" readonly><br>
        <label class="patient-full-detail-label">Appointment Date and Time: </label>
        <span>
        <input class="item-detail" id="date" type="text" value="{{case.appointed_date.date}}" readonly>
        <input class="item-detail" id="time" type="text" value="{{case.appointed_date.time}}" readonly><br>
        </span>
        <form method="post" id="{{case.id}}" class="doctor-patient-form" style="display: flex; flex-direction: column;">
            {% csrf_token %}
            {#{form.id}#}
            <input type="number" name="id" value="{{case.id}}" required="" id="id_id" style="display: none">
            <label class="patient-full-detail-label">Authorise Prescription:</label>
            <!--<input class="item-detail" id="has-prescription" name="has-prescription" type="checkbox"> -->
            {{form.has_pres}}
            <label class="patient-full-detail-label">Diagnosis: </label>
            <!--<textarea class="item-detail" id="diagnosis" cols="16" rows="5" name="diagnosis" placeholder="Your Diagnosis"></textarea>-->
            {{form.desc}}
            <div style="display: flex; flex-direction: row; justify-content: space-between">
            <button class="save-diagnosis-btn" onclick="location.href='view_history?id={{case.patient.id}}'">View History</button>
            <input class="save-diagnosis-btn" type="submit" value="Save">
            </div>
        </form><br>
    </div>
{% endfor %}
</div>

<!--Summary Detail Div-->
<div class="root-container">
    <h3 class="list-title">Doctor's Dashboard</h3><br>
    <h4 class="list-title">Appointed Patients</h4><br>
    <div class="list-container">
        {% if cases %}
        {% for case in cases %}
        <div class="container" onclick="showCaseFull({{case.id}})" style="cursor: pointer">
            <label class="item-detail-label patient-detail-label" onclick="showCaseFull({{case.id}})">Name: </label>
            <input class="item-detail" id="name" type="text" value="{{case.patient.name}}" readonly><br>
            <label class="item-detail-label" onclick="showCaseFull({{case.id}})">Age: </label>
            <input class="item-detail" id="age" type="text" value="{{case.patient.age}}" pattern="[0-9]+" readonly><br>
            <label class="item-detail-label" onclick="showCaseFull({{case.id}})">Gender: </label>
            <input class="item-detail" id="gender" type="text" value="{{case.patient.gender | upper}}" size="1" readonly><br>
            <label class="item-detail-label" onclick="showCaseFull({{case.id}})">Appointment Date: </label>
            <input class="item-detail" id="date" type="text" value="{{case.appointed_date.date}}" onclick="showPatientFull({{case.id}})" readonly>
        </div>
        {% endfor %}
        {%else%}
        <div class="container" style="cursor: pointer">
            <label class="item-detail-label">No Appointments For Today</label>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

{%block script%}
<script>
$(document).ready(function(){
    $(".patient-black-out").hide();
    $(".patient-full-container").hide();
});  

function showCaseFull(caseId) {
    $(".patient-black-out").show();
    $("#"+caseId).show();
}

function closeCaseFull() {
    $(".patient-black-out").hide();
    $(".patient-full-container").hide();
}
</script>
{%endblock%}

doctors/templates/doctors/case-history.html
{%extends "template.html" %}

{% block body %}

<div class="root-container">
    <h3 class="list-title">Patient Case History</h3><br>
    <div>
        <div class="container">
            <label class="case-full-detail-label">Name:</label><br>
            <input class="item-detail" tabindex="-1" id="{{patient.id}}_name" type="text" value="{{patient.name}}" readonly><br>
            <label class="case-full-detail-label">Age:</label><br>
            <input class="item-detail" tabindex="-1" id="{{patient.id}}_age" type="text" value="{{patient.age}}" readonly><br>
            <label class="case-full-detail-label">Gender:</label><br>
            <input class="item-detail" tabindex="-1" id="{{patient.id}}_gender" type="text" value="{{patient.gender | upper}}" readonly>
        </div>
        <div>
        {% if cases %}
        {% for case in cases %}
            <div class="container">
                <label class="case-full-detail-label">Case #{{forloop.counter}}</label><br>
                <span>
                    <label class="case-full-detail-label">Case ID:</label>
                    <input class="item-detail" tabindex="-1" id="{{patient.id}}_{{case.id}}" type="text" value="{{case.id}}" readonly><br>
                    <label class="case-full-detail-label">Assigned Docotr:</label>
                    <input class="item-detail" tabindex="-1" id="{{case.id}}_doctor" type="text" value="{{case.doctor.user.user.username}}" readonly><br>
                    <label class="case-full-detail-label">Appointed Date:</label>
                    <input class="item-detail" tabindex="-1" id="{{case.id}}_date" type="text" value="{{case.appointed_date.date}}" readonly><br>
                    <label class="case-full-detail-label">Appointed Time:</label>
                    <input class="item-detail" tabindex="-1" id="{{case.id}}_time" type="text" value="{{case.appointed_date.time}}" readonly><br>
                        <label class="case-full-detail-label">Diagnosis:</label><br>
                        <textarea class="item-detail" tabindex="-1" id="{{patient.id}}_diagnosis" style="margin-left: 3vw; resize: vertical" cols="87%" rows="6" readonly>{{case.desc}}</textarea>
                </span><br>
                {% if case.prescription.medicine_set.all %}
                <label class="case-full-detail-label">Prescribed Medicines:</label>
                    <ol class="item-detail" style="margin-left: 3vw;">
                        {% for medicine in case.prescription.medicine_set.all %}
                        <li style="margin-left: 2vw;">{{medicine.item.name}} x {{medicine.quantity}}</li>
                        {% endfor %}
                    </ol>
                {%endif%}
                {% if case.prescription.editedprescription.medicines.all %}
                <label> Edited By {{case.prescription.editedprescription.user.user.username}}</label>
                    <ol class="item-detail" style="margin-left: 3vw;">
                        {% for medicine in case.prescription.editedprescription.medicines.all %}
                        <li style="margin-left: 2vw;">{{medicine.item.name}} x {{medicine.quantity}}</li>
                        {% endfor %}
                    </ol>
                {%endif%}
            </div>
        </div>
        {%endfor%}
        {% else %}
        <div class="container">
            <label class="case-full-detail-label">No Previous Cases For Patient</label>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

doctors/templates/doctors/case_archive.html
{%extends "template.html" %}

{% block body %}

<div class="patient-black-out">
    {% for patient, cases in patients.items %}
    <div class="prescription-full-header" id="patient_{{patient.id}}" tabindex="1">
        <span style="display: flex; flex-direction: column">
            <button class="close-full-btn" tabindex="1" onclick="closeCaseFull()">X</button><br>
        </span>
        <label class="case-full-detail-label">Name:</label><br>
        <input class="item-detail" tabindex="-1" id="{{patient.id}}_name" type="text" value="{{patient.name}}" readonly><br>
        <label class="case-full-detail-label">Age:</label><br>
        <input class="item-detail" tabindex="-1" id="{{patient.id}}_age" type="text" value="{{patient.age}}" readonly><br>
        <label class="case-full-detail-label">Gender:</label><br>
        <input class="item-detail" tabindex="-1" id="{{patient.id}}_gender" type="text" value="{{patient.gender | upper}}" readonly>
    </div>
    {% endfor %} 
    
    
    {% for patient, cases in patients.items %}
    {% for case in cases %}
    <div id="case_{{case.id}}" class="case-full-container full-container" tabindex="1">
        <label class="case-full-detail-label">Case #{{forloop.counter}}</label><br>
        <span>
            <label class="case-full-detail-label">Case ID:</label>
            <input class="item-detail" tabindex="-1" id="{{patient.id}}_{{case.id}}" type="text" value="{{case.id}}" readonly><br>
            <label class="case-full-detail-label">Appointed Date:</label>
            <input class="item-detail" tabindex="-1" id="{{case.id}}_date" type="text" value="{{case.appointed_date.date}}" readonly><br>
            <label class="case-full-detail-label">Appointed Time:</label>
            <input class="item-detail" tabindex="-1" id="{{case.id}}_time" type="text" value="{{case.appointed_date.time}}" readonly><br>
                <label class="case-full-detail-label">Diagnosis:</label><br>
                <textarea class="item-detail" tabindex="-1" id="{{patient.id}}_diagnosis" style="margin-left: 3vw; resize: vertical" cols="87%" rows="6" readonly>{{case.desc}}</textarea>
        </span><br>
        {% if case.prescription.medicine_set.all %}
        <label class="case-full-detail-label">Prescribed Medicines:</label>
            <ol class="item-detail" style="margin-left: 3vw;">
                {% for medicine in case.prescription.medicine_set.all %}
                <li style="margin-left: 2vw;">{{medicine.item.name}} x {{medicine.quantity}}</li>
                {% endfor %}
            </ol>
        {%endif%}
        {% if case.prescription.editedprescription.medicines.all %}
        <label> Edited By {{case.prescription.editedprescription.user.user.username}}</label>
            <ol class="item-detail" style="margin-left: 3vw;">
                {% for medicine in case.prescription.editedprescription.medicines.all %}
                <li style="margin-left: 2vw;">{{medicine.item.name}} x {{medicine.quantity}}</li>
                {% endfor %}
            </ol>
        {%endif%}
    </div>
    {% endfor %}
    {% endfor %}
    
</div>
    

<div class="root-container">
    <h3 class="list-title">Patient Archive</h3><br>
    <div class="list-container">
        {% if patients %}
        {% for patient, cases in patients.items %}
        <div class="container">
            <label class="detail-label patient-detail-label">Name: </label>
            <input class="item-detail" id="{{patient.id}}_name" type="text" value="{{patient.name}}" readonly><br>
            <label class="detail-label patient-detail-label">Age: </label>
            <input class="item-detail" id="{{patient.id}}_age" type="text" value="{{patient.age}}" readonly><br>
            <label class="detail-label patient-detail-label">Gender: </label>
            <input class="item-detail" id="{{patient.id}}_gender" type="text" value="{{patient.gender | upper}}" readonly><br>
            <label class="detail-label patient-detail-label">No. Cases: </label>
            <input class="item-detail" id="{{patient.id}}_cases" type="text" value="{{cases.count}}" readonly><br>
            <div>
                <label class="prescriptions-label">Cases:</label>
                <div class="prescriptions-list" style="overflow: scroll; height: 15vh;">
                    {% for case in cases %}
                    <div class="case" onclick="showCaseFull({{case.id}}, {{patient.id}})">
                        <label>Case #{{forloop.counter}}</label>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <button class="item-detail" onclick="location.href='view_history?id={{patient.id}}'">View History</button>
        </div>
        {% endfor %}
        {% else %}
        <div class="container">
            <label class="detail-label patient-detail-label">No Patients Handled Yet</label>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

{%block script%}
<script>
    
$(document).ready(function(){
    $(".patient-black-out").hide();
    $(".prescription-full-header").hide();
    $(".case-full-container").hide();
});    
    
function showCaseFull(caseID, patientID) {

    $(".patient-black-out").show();
    
    $("#patient_"+patientID).show();
    
    $("#case_"+caseID).show();
    
}

function closeCaseFull() {
    
    $(".patient-black-out").hide();
    
    $(".prescription-full-header").each(function(index, patient){
       patient.style.display = "none";
    });
    
    $(".case-full-container").each(function(index, item){
       item.style.display = "none";
    });
}
</script>
{%endblock%}

doctors/templates/doctors/prescription.html
{%extends "template.html"%}

{%block body%}
<div class="root-container">
    <h3 class="list-title">Patient Prescription</h3><br>
    {% if prescriptions %}
    {% for pres in prescriptions %}
    <div class="container">
        <label class="patient-detail-label">Patient Name:</label>
        <input class="item-detail" id="{{pres.case.id}}_name" type="text" value="{{pres.case.patient.name}}" readonly><br>
        <label class="item-detail-label">Case ID:</label>
        <input class="item-detail" id="{{pres.case.id}}_id" type="text" value="{{pres.case.id}}" readonly><br>
        <label class="item-detail-label">Date:</label>
        <input class="item-detail" id="{{pres.case.id}}_id" type="text" value="{{pres.case.appointed_date.date}}" readonly><br>
        <label class="item-detail-label">Time:</label>
        <input class="item-detail" id="{{pres.case.id}}_id" type="text" value="{{pres.case.appointed_date.time}}" readonly><br>
        <label class="patient-detail-label">Diagnosis:</label>
        <textarea class="item-detail" readonly style="resize: vertical">{{pres.case.desc}}</textarea>
        <button class="item-detail" onclick="redirectToAdd({{pres.case.id}})">Edit Prescription</button>
    </div>
    {% endfor %}
    {% else %}
    <div class="container">
        <label class="item-detail-label">No Unsaved Prescriptions</label>
    </div>
    {% endif %}
</div>
{%endblock%}

{%block script%}
<script>

    function redirectToAdd(caseId) {
        
        $.ajax({
            url: "{% url 'doctor:add_prescription' %}",
            data: {
                'id': caseId
            },
            type: 'GET',
            success: function(){
                document.location = "{% url 'doctor:add_prescription' %}?id=" + caseId;
            }
        });
        
    }
    
</script>
{%endblock%}