admins/urls.py
from django.urls import path
from . import views

app_name = 'admins'
urlpatterns = [
    path('attendance', views.attendance, name="attendance"),
    path('create_patient', views.create_patient, name="create_patient"),
    path('edit_patient', views.edit_patient, name="edit_patient"),
    path('create_cases', views.create_case, name="create_case"),
    path('edit_cases', views.edit_case, name="edit_case"),
    path('list_patients', views.list_patients, name="list_patients"),
    path('list_cases', views.list_cases, name="list_cases")
]

api/urls.py
from django.urls import path, include
from pharma import api_views
from rest_framework.authtoken import views
from .views import ping, csrf

urlpatterns = [
   path('api-token-auth/', views.obtain_auth_token),
   path('api-auth/', include('rest_framework.urls')),
   path('last-pres', api_views.LastPrescriptionView.as_view()),
   path('stock', api_views.ListStockView.as_view()),
   path('csrf', csrf),
   path('ping', ping),
]

med_bay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from admins.views import LoginView, confirm_logout, home, redirect_login, set_theme

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('staff/', include('admins.urls')),
    path('doctor/', include('doctors.urls')),
    path('pharmacy/', include('pharma.urls')),
    path('accounts/', include('accounts.urls')),
    path("login", LoginView.as_view(template_name="admins/login.html"), name="login"),
    path("logout", LogoutView.as_view(template_name="admins/logout.html"), name="logout"),
    path("confirm", confirm_logout, name='confirm_logout'),
    path("", home, name="home"),
    path("redirect", redirect_login, name="red"),
    path("set_theme", set_theme, name="set_theme")
]


handler404 = 'med_bay.error_views.error_404_handler'
handler403 = 'med_bay.error_views.error_403_handler'

admins/templates/admins/attendance.html
{%extends "template.html"%}

{%block body%}
<table class="attendance-table">
    <tr>
        <th style="width: 2vw; height: 7vh">S.No.</th>
        <th>Name</th>
        <th style="width: 1vw">Attendance</th>
    </tr>
    {% if doctors %}
    {% for doctor in doctors %}
    <tr>
        <th>{{forloop.counter}}.</th>
        <td id="doctor-name-attendance" style="color: white;">{{doctor.user.username}}</td>
        <td style="padding: 0;" class="checkbox-container">
            <span class="attendance-custom-checkbox" id="{{doctor.id}}" onclick="toggleAttendance({{doctor.id}})"></span>
        </td>
    </tr>
    {%endfor%}
    {% else %}
    <tr>
        <td> </td>
        <td id="doctor-name-attendance" style="color: white;"> No Doctors Registered </td>
        <td> </td>
    </tr>
    {% endif %}
    <tr>
        <td> </td>
        <td><button id="submit-btn" onclick="submitAttendance()">Submit</button></td>
        <td> </td>
    </tr>
</table>
{%endblock%}

{%block script%}
<script>
    function toggleAttendance(doctorID){
        $(".attendance-custom-checkbox").each(function(index, checkbox) {
            if (checkbox.id == parseInt(doctorID)){
                checkbox.classList.toggle("true");
            }
        });
    }

    function submitAttendance(){
        var doctorAttendance = {};

        $(".attendance-custom-checkbox").each(function(index, checkbox) {
            if (checkbox.classList.contains("true")){
                doctorAttendance[parseInt(checkbox.id)] = true;
            } else {
                doctorAttendance[parseInt(checkbox.id)] = false;
            }
        });

        $.ajax({

            url: "{% url 'admins:attendance' %}",
            data: {
                'update': true,
                'attendance': JSON.stringify(doctorAttendance),
            },
            success: function(){
                showMessage("Attendance saved");
                location="{% url 'home' %}"
            },
            error: function(){
                showMessage("Unable to save attendance");
            }
        });
    }
</script>
{%endblock%}

admins/templates/admins/confirm-signout.html
{%extends "template.html"%}

{%block body%}
<div class="error-root">
    <h1>You have signed out</h1>
    <span>
        <h1>Click the button to login</h1>
        <button style="background-color: #E00043; padding: 1vh 1vw 1vh 1vw; font-size: 3vh; border-radius: 8px;">Login</button>
    </span>
</div>
{%endblock%}

admins/templates/admins/confirm_logout.html
{%extends "template.html"%}

{%block body%}
<div class="error-root">
    <span>
        <h1 style="display: inline;">You're already signed in as {{user}}</h1><h1 id="role" style="display: inline;"></h1>
        <span id="account-role" style="display: none;">{{user.staff.role}}</span>
    </span>
    <span>
        <h1>If you wish to login with another account please sign out</h1>
        <button class="default-button" style="padding: 1vh 1vw 1vh 1vw; font-size: 3vh; border-radius: 8px;" onclick="document.location='{% url 'logout' %}'">Sign Out</button>
    </span>
</div>
{%endblock%}

{%block script%}
<script>
$(document).ready(function(){
    var meta = $('#account-role');
    
    role = meta.text();
    
    if (role === "d") {
        role = " (Doctor)";
    } else if (role === "p") {
        role = " (Pharmacy Manager)";
    }  else if (role === "ac") {
        role = " (Accountant)";
    } else if (role === "a") {
        role = " (Admin)";
    }
    
    $('#role').text(role);
});
</script>
{%endblock%}

admins/templates/admins/create_case.html
{% extends 'template.html' %}

{% block body %}
<div id="form-window">
    <div id="form-title">
        <label id="form-label">{{title}} Case</label>
    </div>
    <form id="form" method="post">
        {% csrf_token %}
        <label>Select Patient:</label><br>
        {{form.patient}}
        <label>Asign to Doctor:</label><br>
        {{form.doctor}}
        <label>Appointment Date and Time:</label><br>
        {{form.date}}
        <label>Priority:</label><br>
        {{form.state}}
        <input type="submit" id="submit-btn" value="Submit">
    </form>
</div>
{% endblock %}

admins/templates/admins/create_patient.html
{% extends 'template.html' %}

{% block body %}
<div id="form-window">
    <div id="form-title">
        <label id="form-label">{{title}} Patient</label>
    </div>
    <form id="form" method="post">
        {% csrf_token %}
        <label>Name:</label><br>
        {{form.name}}
        <label>Age:</label><br>
        {{form.age}}
        <label>Gender:</label><br>
        {{form.gender}}
        <label>Blood Group:</label><br>
        {{form.blood_type}}
        <label>Email:</label><br>
        {{form.email}}
        <label>Phone:</label><br>
        {{form.phone}}
        <input type="submit" id="submit-btn" value="Submit">
    </form>
</div>
{% endblock %}

admins/templates/admins/home.html
{%extends "template.html"%}
{% load static %}

{%block body%}
<div class="home-root">
	<h1>Welcome</h1>
	{% if not request.user.is_authenticated %}
	<h3>Login</h3>
	{% else %}
	<h3>You are logged in as</h3>
	{%endif%}
	<div class="home-container">
		{% if not request.user.is_authenticated %}
		<img src="{% static 'images/user.png' %}" alt="user icon"><br>
		<button class="login-logout-btn default-button" style="background-color: rgba(0, 0, 0, 0.2); padding: 1vh 1vw 1vh 1vw; font-size: 3vh; border-radius: 8px;" onclick="document.location='{% url 'login' %}'">Log In</button>
		{% else %}
		<img src="{% static 'images/user_loggedin.png' %}" alt="user icon"><br>
		<span style="color: white; font-size: large;">
			<label>{{user}}</label> <label id="role" style="display: inline;"></label><br><br>
			<span id="account-role" style="display: none;">{{user.staff.role}}</span>
		</span>
		<button class="login-logout-btn default-button" style="background-color: rgba(0, 0, 0, 0.2); padding: 1vh 1vw 1vh 1vw; font-size: 3vh; border-radius: 8px;" onclick="document.location='{% url 'logout' %}'">Log Out</button>
		{%endif%}
	</div>
</div>
{%endblock%}

{%block script%}
<script>
$(document).ready(function(){
    var meta = $('#account-role');
    
    role = meta.text();
    
    if (role === "d") {
        role = "(Doctor)";
    } else if (role === "p") {
        role = "(Pharmacy Manager)";
    } else if (role === "ac") {
        role = "(Accountant)";
    } else if (role === "a") {
        role = "(Admin)";
    }
    
    $('#role').text(role);
});
</script>
{%endblock%}

admins/templates/admins/list_cases.html
{%extends "template.html"%}

{% block body %}
<div class="root-container">
    <h3 class="list-title">Cases List</h3><br>
    <div class="list-container">
    {% if cases %}
    {% for case in cases %}
        <div id="{{case.id}}" class="container" style="width: 20vw;">
            <h4>Case #{{case.id}}</h4>
            <label class="patient-detail-label">Patient:</label>
            <input class="item-detail" value="{{case.patient.name}}" readonly>
            <label class="patient-detail-label">Doctor:</label>
            <input class="item-detail" value="{{case.doctor.user.user.username}}" readonly>
            <label class="patient-detail-label">Appointment Date:</label>
            <input class="item-detail" value="{{case.appointed_date}}" readonly>
            <label class="item-detail-label">Priority:</label>
            {% if case.state == "n" %}
            <input class="item-detail" value="Normal" readonly>
            {% elif case.state == "c" %}
            <input class="item-detail" value="Check Up" readonly>
            {% elif case.state == "e" %}
            <input class="item-detail" value="Emergency" readonly>
            {%endif%}
            <span>
            <button class="item-detail" onclick="editCase({{case.id}})" style="width: 45%; margin-right: 2.5%">Edit Case</button><button class="item-detail" onclick="deleteCase({{case.id}})" style="width: 45%; margin-left: 2.5%">Delete Case</button>
            </span>
        </div>
    {%endfor%}
    {% else %}
    <div class="container">
        <label class="item-detail-label">No Cases Created</label>
    </div>
    {% endif %}
        <div class="container" style="width: 20vw;" onclick="location='{% url 'admins:create_case' %}'">
            <h1 style="margin: auto">+</h1>
        </div>
    </div>
</div>
{%endblock%}

{% block script %}
<script>
    function editCase(caseId) {
        location = "{% url 'admins:edit_case' %}?id="+caseId;
    }

    function deleteCase(caseId) {

        if(confirm("Are You Sure You Want To Delete Case No."+caseId+"?")) {
            $.ajax({
                url: "{% url 'admins:list_cases' %}",
                data: {
                    'delete_id': caseId
                },
                success: function(){
                    showMessage("Case No." + caseId + " Has Been Deleted");
                    location.reload();
                },
                error: function(error){
                    showMessage("Could Not Delete Case");
                }
            });
        }
    }
</script>
{%endblock%}

admins/templates/admins/list_patients.html
{%extends "template.html"%}

{% block body %}
<div class="root-container">
    <h3 class="list-title">Patients List</h3><br>
    <div class="list-container">
    {% if patients %}
    {% for patient in patients %}
        <div id="{{patient.id}}" class="container" style="width: 20vw;">
            <label class="patient-detail-label">Patient Name:</label>
            <input class="item-detail" value="{{patient.name}}" readonly>
            <label class="patient-detail-label">Age:</label>
            <input class="item-detail" value="{{patient.age}}" readonly>
            <label class="patient-detail-label">Gender:</label>
            <input class="item-detail" value="{{patient.gender|upper}}" readonly>
            <input class="item-detail" value="{{patient.email}}" readonly>
            <input class="item-detail" value="{{patient.phone}}" readonly>
            <button class="item-detail" onclick="editPatient({{patient.id}})">Edit Patient</button>
        </div>
    {%endfor%}
    {% else %}
    <div class="container">
        <label class="item-detail-label">No Patients Created</label>
    </div>
    {% endif %}
    </div>
</div>
{%endblock%}

{% block script %}
<script>
function editPatient(patientId) {
    location = "{% url 'admins:edit_patient' %}?id="+patientId;
}
</script>
{%endblock%}

admins/templates/admins/login.html
{%extends "template.html" %}
{% block body %}


<div id="form-window">
    <div id="form-title">
        <label id="form-label">Staff Login</label>
    </div>
    <span id="form-error">{{form.non_field_errors.as_text}}</span>
    <form id="form" method="post">
        {% csrf_token %}
<!--        <label id="username-label" for="username">Username:</label><br>-->
<!--        <input class="login-input" type="text" id="username" name="username" placeholder="Username" required autofocus><br> -->
        {{form.username}}
<!--        <label id="password-label" for="password">Password:</label><br>-->
<!--        <input class="login-input" type="password" id="password" name="password" placeholder="Password" required><br> -->
        {{form.password}}
        <input id="submit-btn" type="submit" value="Login">
    </form>
</div>
{%endblock%}

admins/templates/admins/logout.html
{%extends "template.html"%}

{%block body%}
<div class="error-root">
    <h1>You have signed out</h1>
    <span>
        <h1>Click the button to login</h1>
        <button class="default-button" style="padding: 1vh 1vw 1vh 1vw; font-size: 3vh; border-radius: 8px;" onclick="document.location='{% url 'login' %}'">Login</button>
    </span>
</div>
{%endblock%}